{
 "title": "Prometheus",
 "description": "Dashboard providing insight to Prometheus monitoring system status and it's runtime info.",
 "tags": [
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "aggregation_interval",
    "label": "Aggregation intarval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "query_result({__name__=~\"prometheus_.*_seconds\"})"
   },
   {
    "name": "long_term_interval",
    "query": "10m,30m,1h,6h,12h,1d,3d,1w,4w,12w,1y"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://cdn.worldvectorlogo.com/logos/prometheus.svg\"/ height=\"140px\">"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Build, uptime and runtime instance info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{job=\"prometheus\"}) by (instance)"
    },
    {
     "expr": "max(prometheus_build_info{job=\"prometheus\"}) by (instance, branch, goversion, version, revision)"
    },
    {
     "expr": "max(prometheus_config_last_reload_successful{job=\"prometheus\"}) by (instance)"
    },
    {
     "expr": "max(sum(prometheus_rule_group_rules{job=\"prometheus\"}) by (instance) or prometheus_build_info{job=\"prometheus\"}*0) by (instance)"
    },
    {
     "expr": "max(sum(prometheus_sd_discovered_targets{job=\"prometheus\", name=\"scrape\"}) by (instance) or prometheus_build_info{job=\"prometheus\"}*0) by (instance)"
    },
    {
     "expr": "max(prometheus_tsdb_head_series{job=\"prometheus\"}) by (instance)"
    },
    {
     "expr": "time() - max(prometheus_tsdb_lowest_timestamp_seconds{job=\"prometheus\"}) by (instance)"
    },
    {
     "expr": "min(prometheus_tsdb_storage_blocks_bytes{job=\"prometheus\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Main info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_series{job=\"prometheus\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of interval length between scrapes per job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{job=\"prometheus\",quantile=\"$quantile\"}",
     "legendFormat": "job {{job}} should be {{interval}}"
    }
   ]
  },
  {
   "title": "Prometheus errors in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(label_replace({__name__=~\"(:?prometheus|net_conntrack)_.*(:?fail|duplicate|out_of|error|not_found|corrupt|dropped|missed|exceeded).*_total\", job=\"prometheus\"}, \"metric_name\", \"$1\", \"__name__\", \"(.*)\")[$aggregation_interval:20s])) by (instance,metric_name,alertmanager,name,mechanism,queue) > 0"
    }
   ]
  },
  {
   "title": "Requests & queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP request count by handler in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_http_requests_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, handler)",
     "legendFormat": "{{ handler }} handler on {{ instance }}"
    }
   ]
  },
  {
   "title": "$quantile quantile of HTTP request duration per handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_request_duration_seconds_bucket{job=\"prometheus\"}[$aggregation_interval])) by (le,instance, handler))",
     "legendFormat": "{{ handler }} handler on {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of request size by handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_response_size_bytes_bucket{job=\"prometheus\"}[$aggregation_interval])) by (le,instance, handler)) > 0",
     "legendFormat": "{{ handler }} handler on {{ instance }}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "CPU usage of {{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Resident memory of {{instance}}"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Total allocated bytes of {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations per second in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[$aggregation_interval])",
     "legendFormat": "Allocated Bytes of {{instance}}"
    }
   ]
  },
  {
   "title": "TSDB stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oldest data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - min(prometheus_tsdb_lowest_timestamp_seconds{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Oldest data for {{instance}}"
    }
   ]
  },
  {
   "title": "Size of the storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes{job=\"prometheus\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Query engine & API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of concurent queries and it's limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_engine_queries{job=\"prometheus\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(prometheus_engine_queries_concurrent_max{job=\"prometheus\"}) by (instance)",
     "legendFormat": "{{instance}} Limit"
    }
   ]
  },
  {
   "title": "$quantile quantile of query engine evaluation duration per slice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"$quantile\"}",
     "legendFormat": "{{slice}} slice on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of queries on remote read API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_api_remote_read_queries{job=\"prometheus\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rule evaluation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(20,max(prometheus_rule_group_last_duration_seconds{job=\"prometheus\"}) by (rule_group, instance) / min(prometheus_rule_group_interval_seconds{job=\"prometheus\"}) by (rule_group, instance))",
     "legendFormat": "Percentage of {{rule_group}} group evaluation interval on {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of rule evaulation duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_rule_evaluation_duration_seconds{job=\"prometheus\", quantile=\"$quantile\"}) by (instance, quantile)",
     "legendFormat": "evaluation duration of {{instance}}"
    }
   ]
  },
  {
   "title": "Number of rules per group (top 20 groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(20,prometheus_rule_group_rules{job=\"prometheus\"})) by (instance, rule_group)",
     "legendFormat": "number of rules in {{rule_group}} rule group on {{instance}}"
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Notification queue size and capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_notifications_queue_length{job=\"prometheus\"})by (instance)",
     "legendFormat": "Queue size of {{instance}}"
    },
    {
     "expr": "sum(prometheus_notifications_queue_capacity{job=\"prometheus\"})by (instance)",
     "legendFormat": "Queue capacity of {{instance}}"
    }
   ]
  },
  {
   "title": "Number of sent notifictions per alertmanager in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_notifications_sent_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, alertmanager)",
     "legendFormat": "Sent notifications to {{alertmanager}} alertmanager from {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile of notification latency per alertmanager",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_notifications_latency_seconds{job=\"prometheus\", quantile=\"$quantile\"}) by (instance, alertmanager)",
     "legendFormat": "Latency of notifications sent to {{alertmanager}} from  {{instance}}"
    }
   ]
  },
  {
   "title": "Service discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of discovered targets per Type and config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=\"prometheus\", name=\"scrape\"}) by (instance, config,name)",
     "legendFormat": "Number of {{name}} type targets from config {{config}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Service discovery  sync count by mechanism in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_sd_refresh_duration_seconds_count{job=\"prometheus\"}[$aggregation_interval])) by (instance, mechanism)",
     "legendFormat": "Number of sync for {{mechanism}} SD mechanism on {{instance}}"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_duration_seconds_count{job=\"prometheus\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "Number of sync for consul SD mechanism on {{instance}}"
    },
    {
     "expr": "sum(increase(prometheus_sd_kubernetes_http_request_duration_seconds_count{job=\"prometheus\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "Number of sync for kubernetes SD mechanism on {{instance}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of refresh duration per SD mechanism",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_sd_refresh_duration_seconds{job=\"prometheus\", quantile=\"$quantile\"}",
     "legendFormat": "Duration of sync for {{mechanism}} SD mechanism on {{instance}}"
    },
    {
     "expr": "consul_rpc_duration_seconds{job=\"prometheus\", quantile=\"$quantile\"}",
     "legendFormat": "Number of sync for consul SD mechanism on {{instance}}"
    },
    {
     "expr": "prometheus_sd_file_scan_duration_seconds{job=\"prometheus\", quantile=\"$quantile\"}",
     "legendFormat": "Duration of sync for file_scan SD mechanism on {{instance}}"
    },
    {
     "expr": "prometheus_sd_kubernetes_http_request_duration_seconds_sum{job=\"prometheus\"} / prometheus_sd_kubernetes_http_request_duration_seconds_count{job=\"prometheus\"}",
     "legendFormat": "AVG Duration of sync for k8s SD mechanism on {{instance}}"
    }
   ]
  },
  {
   "title": "Compaction and retention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$quantile quantile of compaction duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{job=\"prometheus\"}[$aggregation_interval])) by (instance, le))",
     "legendFormat": "Compaction duration on {{ instance }}"
    }
   ]
  },
  {
   "title": "Number of vertical/horizontal compactions in last $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_total{job=\"prometheus\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "Count of horizontal compactions on {{instance}}"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_vertical_compactions_total{job=\"prometheus\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "Count of vertical compactions  on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of time/size retention cutoffs in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_size_retentions_total{job=\"prometheus\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "Number of size retention cutoffs on  {{ instance }}"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_time_retentions_total{job=\"prometheus\"}[$aggregation_interval])) by (instance) > 0",
     "legendFormat": "Number of time retention cutoffs on {{ instance }}"
    }
   ]
  },
  {
   "title": "Head block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head chunks count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Head block chunk count on {{instance}}"
    }
   ]
  },
  {
   "title": "Samples Appended per second in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "Appended samples/s on {{instance}}"
    }
   ]
  },
  {
   "title": "Time series total count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\"}",
     "legendFormat": "Time series count of  {{instance}}"
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$quantile quantile of WAL fsync duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_wal_fsync_duration_seconds{job=\"prometheus\",quantile=\"$quantile\"}) by (instance)",
     "legendFormat": "Duration of WAL fsync on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of completed pages in $aggregation_interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_wal_completed_pages_total{job=\"prometheus\"}[$aggregation_interval])) by (instance)",
     "legendFormat": "Completed WAL pages count of {{instance}}"
    }
   ]
  },
  {
   "title": "Average duration of WAL truncation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\"} /prometheus_tsdb_wal_truncate_duration_seconds_count{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Duration of WAL truncation on {{instance}}"
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of gorutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"prometheus\"}) by (instance)",
     "legendFormat": "Gorutines count of {{instance}}"
    }
   ]
  },
  {
   "title": "Duration of Go garbage collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(go_gc_duration_seconds{job=\"prometheus\"}) by (instance)",
     "legendFormat": "GC duration on {{instance}}"
    }
   ]
  },
  {
   "title": "Go system memory allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(go_memstats_mspan_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "mspan {{instance}}"
    },
    {
     "expr": "max(go_memstats_mcache_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "mcache {{instance}}"
    },
    {
     "expr": "max(go_memstats_buck_hash_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "buck_hash {{instance}}"
    },
    {
     "expr": "max(go_memstats_gc_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "gc {{instance}}"
    },
    {
     "expr": "max(go_memstats_other_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "other {{instance}}"
    },
    {
     "expr": "max(go_memstats_stack_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "stack {{instance}}"
    },
    {
     "expr": "max(go_memstats_heap_sys_bytes{job=\"prometheus\"}) by (instance)",
     "legendFormat": "heap {{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accepted/closed inbound connections per listener",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_listener_conn_accepted_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, listener_name) > 0",
     "legendFormat": "{{listener_name}} accepted connections on {{instance}}"
    },
    {
     "expr": "sum(increase(net_conntrack_listener_conn_closed_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, listener_name) > 0",
     "legendFormat": "{{listener_name}} closed connections on {{instance}}"
    }
   ]
  },
  {
   "title": "Established/closed outbound connections per dialer ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_established_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, dialer_name) > 0",
     "legendFormat": "{{dialer_name}} established connections on {{instance}}"
    },
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_closed_total{job=\"prometheus\"}[$aggregation_interval])) by (instance, dialer_name) > 0",
     "legendFormat": "{{dialer_name}} closed connections on {{instance}}"
    }
   ]
  }
 ]
}